# -*- coding: utf-8 -*-
"""helper_functions.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/124BUmDD6w-MH7g5mNPX_VlwCBP_9PvVo

# DATA STRUCTURES HELPER FUNCTIONS
# This script contains all the functions from the AltSchool Africa Tinyuka cohort 1st semester Objects and Data Structures Assessment Test
"""

# STRINGS
# Define the string
s = "hello world"

# Extract every second letter
letter_sequence = s[::2]

# Format the greeting
# This remains unformatted and will be formatted in assertions
# to match the expected test case.
greeting = "Hello {}, you are {} years old"

# LISTS
list3 = [1, 2, [3, 4, 'hello']]

# Modify "hello" to "goodbye"
list3[2][2] = "goodbye"

# Append 100
list3.append(100)

# Remove 2
list3.remove(2)

# Reverse the list (matching the assert statement naming)
modiFied = list3[::-1]

# DICTIONARIES
d = {"k1": [{"nest_key": ["this is deep", ["hello"]]}], "age": 30}

# Extract "hello"
dict_answer = d['k1'][0]['nest_key'][1][0]

# Add new key "name" with value "Alice"
d['name'] = 'Alice'

# Increase "age" by 5
d['age'] += 5

# TUPLES
# Define a tuple
my_tuple = (5, 15, 3)

# Unpack tuple
a, b, c = my_tuple

# Concatenate with another tuple
new_tuple = my_tuple + (4, 5, 6)

# SETS
list5 = [1,2,2,33,4,4,11,22,3,3,2]

# Convert to set to get unique values
unique_values = set(list5)